name: Validate

on: 'push'

jobs:
  validate-build-windows:
    name: "Validate (Windows)"
    runs-on: windows-latest
    strategy:
      matrix:
        channel: [stable, docking]
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository
      run: |
        pip install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Build
      run: |
        conan create . imgui/1.77@iceshard/${{ matrix.channel }}
